[tool.poetry]
name = "online-crowd-analyzer"
version = "0.1.0"
description = ""
authors = ["Topvennie <vincent@vallaeys.com>"]
license = "MIT License"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
ultralytics = "8.2.2"
tensorflow = "2.13.1"
protobuf = "3.20.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
